CREATE TABLE BOARD(
	BOARDNUM INT PRIMARY KEY,
	ID VARCHAR(100),
	CATEGORY VARCHAR(100) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(500) NOT NULL,
	BOARDDATE DATE DEFAULT SYSDATE,
	PRICE INT,
	IMAGE VARCHAR(300),
	PRODUCTCATEGORY VARCHAR(100),
	COMPANY VARCHAR(100),
	STATE VARCHAR(100),
	VIEWCOUNT INT,
	COMMENDNUM INT
);


SELECT * FROM (SELECT B.*, ROWNUM FROM ( SELECT A.* FROM ( SELECT * FROM BOARD WHERE 1=1 )A)B);
SELECT BOARD.BOARDNUM, MEMBER.ID, BOARD.CATEGORY, BOARD.TITLE, 
			TO_CHAR(BOARD.BOARDDATE, 'YYYY-MM-DD') AS BOARDDATE, BOARD.STATE, BOARD.PRICE, BOARD.VIEWCOUNT, RECOMMEND.RECOMMENDNUM, MEMBER.NICKNAME, MEMBER.ID, 
			COUNT(BOARD.BOARDNUM) AS CNT FROM BOARD 
			LEFT JOIN MEMBER ON BOARD.ID = MEMBER.ID 
			LEFT JOIN RECOMMEND ON BOARD.BOARDNUM = RECOMMEND.BOARDNUM WHERE CATEGORY = '리뷰'
			GROUP BY BOARD.BOARDNUM, BOARD.PRICE, MEMBER.ID, BOARD.CATEGORY, BOARD.TITLE, BOARD.BOARDDATE, 
			BOARD.STATE, BOARD.VIEWCOUNT, RECOMMEND.RECOMMENDNUM, MEMBER.NICKNAME, MEMBER.ID 
			ORDER BY BOARD.BOARDNUM DESC;


DELETE FROM BOARD;
 
DROP TABLE BOARD;
DROP TABLE RECOMMEND;
DROP TABLE REVIEW;
DROP TABLE MEMBER;
INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','리뷰','카메라리뷰','카메라가좋아요',1000,'캐논');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','리뷰','카메라리뷰합니다~','카메라가좋아요',2000,'캐논');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','리뷰','카메라리뷰한다고!!!','카메라가좋아요',3000,'캐논');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','리뷰','카메라리뷰보세요~','카메라가좋아요',4000,'니콘');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','리뷰','카메라리뷰중~~~','카메라가좋아요',5000,'니콘');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','리뷰','카메라리뷰해용','카메라가좋아요',6000,'니콘');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','판매','판매글1','카메라가좋아요',7000,'소니');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','판매','판매글2','카메라가좋아요',8000,'소니');
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS,PRICE,COMPANY)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'a@a.c','자유게시판','자유게시글','카메라가좋아요',9000,'소니');
	
	INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'c@c.c','리뷰','CANON카메라리뷰','카메라가좋아요');
		INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'c@c.c','리뷰','PENTAX카메라리뷰','카메라가좋아요');
		INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'c@c.c','리뷰','캐논카메라리뷰','카메라가좋아요');
		INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'c@c.c','리뷰','LEICA카메라리뷰','카메라가좋아요');
		INSERT INTO BOARD(BOARDNUM,ID,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'c@c.c','리뷰','KONICA카메라리뷰','카메라가좋아요');
	