
CREATE TABLE MEMBER(
	MEMBERNUM INT PRIMARY KEY,
	ID VARCHAR(100) UNIQUE NOT NULL,
	PW VARCHAR(100) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	NICKNAME VARCHAR(100) UNIQUE NOT NULL,
	BIRTH DATE DEFAULT SYSDATE,
	PH VARCHAR(100) UNIQUE,
	PROFILE VARCHAR(500),
	GRADE VARCHAR(100)
)









-------------------------------QUERY TEST---------------------------------
SELECT * FROM MEMBER WHERE NICKNAME LIKE '진%';
SELECT * FROM MEMBER;
DELETE FROM MEMBER;
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,PROFILE,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'a@a.c','a','석진','진',(TO_DATE('19930910','YYYY-MM-DD')),'010-1234-5678','1.png','일반');
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,PROFILE,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'b@b.c','b','티모','티모모',(TO_DATE('19930910','YYYY-MM-DD')),'010-1232-5678','2.png','일반');
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,PROFILE,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'IRONMAN@gmail.com','123123123','아이언맨','아이언맨짱',(TO_DATE('19930910','YYYY-MM-DD')),'010-1234-5678','1.jpg','일반');
																																				--뭐 어떻게 받아야돼???
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,PROFILE,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'1','1234','아','나',(TO_DATE('19930910','YYYY-MM-DD')),'01022222222','jpg','일반');
		
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'CAPTAIN','1234','캡틴','캡틴큐','1995-08-16','01055555555','신입');
	
INSERT INTO MEMBER(MEMBERNUM,ID,PW,NAME,NICKNAME,BIRTH,PH,GRADE)
	VALUES((SELECT NVL(MAX(MEMBERNUM),0)+1 FROM MEMBER),'THANOS','1234','타노스','반반맨','1995-08-17','01066666666','관리자');
	
	SELECT M.MEMBERNUM,ID,PW,NAME,NICKNAME, TO_CHAR(BIRTH,'YYYY-MM-DD'),PH,PROFILE,GRADE, BOARDNUM, TITLE FROM MEMBER M LEFT JOIN BOARD B ON M.MEMBERNUM = B.MEMBERNUM WHERE ID='b@b.c';
DROP TABLE MEMBER;
DELETE FROM BOARD;

INSERT INTO BOARD(BOARDNUM, MEMBERNUM, CATEGORY, TITLE, CONTENTS) VALUES((SELECT NVL(MAX(BOARDNUM),0) FROM BOARD)+1, 1, '자유게시판','카메라안삼~','사실 삼 ...');
SELECT * FROM ALL_TABLES;

CREATE TABLE BOARD(
	BOARDNUM INT PRIMARY KEY,
	MEMBERNUM INT,
	CATEGORY VARCHAR(100) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENTS VARCHAR(500) NOT NULL,
	BOARDDATE DATE DEFAULT SYSDATE,
	PRICE INT,
	IMAGE VARCHAR(300),
	PRODUCTCATEGORY VARCHAR(100),
	COMPANY VARCHAR(100),
	STATE VARCHAR(100),
	VIEWCOUNT INT,
	RECOMMENDNUM INT
);

SELECT * FROM BOARD;
DROP TABLE BOARD;
DELETE FROM BOARD;
INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','a','제목','내용');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','자유게시판','집가고싶다','집보내줘');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'1','사진자랑','오소리티모','귀엽다');

	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'2','티모자랑','칼바조아','카메라팔아용');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'2','티모자랑','칼바조아','카메라팔아용');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'2','사진자랑','칼바조아','카메라팔아용');
	INSERT INTO BOARD(BOARDNUM,MEMBERNUM,CATEGORY,TITLE,CONTENTS)
	VALUES((SELECT NVL(MAX(BOARDNUM),0)+1 FROM BOARD),'2','사진자랑','칼바조아','카메라팔아용');
	
	CREATE TABLE RECOMMAND(
	RECOMMANDNUM INT PRIMARY KEY,
	BOARDNUM INT,
	MEMBERNUM INT
--	FOREIGN KEY (BOARDNUM) REFERENCES BOARD(BOARDNUM)
);	

SELECT * FROM RECOMMAND;
INSERT INTO RECOMMAND(RECOMMANDNUM, BOARDNUM, MEMBERNUM)
	VALUES((SELECT NVL(MAX(RECOMMANDNUM),0)+1 FROM RECOMMAND),'1','1');
	
	
	-- 멤버는 있어도 게시글은 없을 수 있고... 게시글은 있어도 댓글은 없을 수 있다...
	-- 따라서 inner join이 아닌 outer join을 사용해서 없는 정보라도 일단 조인은 되게 하여야
	-- 다른 정보들을 가지고 올 수 있다 ...
	SELECT BOARD.BOARDNUM, MEMBER.MEMBERNUM, BOARD.CATEGORY, BOARD.TITLE, TO_CHAR(BOARD.BOARDDATE, 'YYYY-MM-DD') AS BOARDDATE, BOARD.STATE, BOARD.VIEWCOUNT, MEMBER.NICKNAME, MEMBER.ID, COUNT(BOARD.BOARDNUM) AS CNT
	FROM BOARD 
	LEFT JOIN MEMBER ON BOARD.MEMBERNUM = MEMBER.MEMBERNUM
	LEFT JOIN RECOMMAND ON BOARD.BOARDNUM = RECOMMAND.BOARDNUM
	WHERE MEMBER.NICKNAME LIKE '진%'
	GROUP BY BOARD.BOARDNUM, MEMBER.MEMBERNUM, BOARD.CATEGORY, BOARD.TITLE, BOARD.BOARDDATE, 
	BOARD.STATE, BOARD.VIEWCOUNT, MEMBER.NICKNAME, MEMBER.ID 
	ORDER BY BOARD.BOARDNUM DESC;	
	
		// 게시글 검색 기능 - 작성자(NICKNAME)로 검색
	private static final String SELECTALL_SEARCHWRITER = "SELECT BOARD.BOARDNUM, MEMBER.MEMBERNUM, BOARD.CATEGORY, "
			+ "BOARD.TITLE, TO_CHAR(BOARD.BOARDDATE, 'YYYY-MM-DD') AS BOARDDATE, BOARD.STATE, BOARD.VIEWCOUNT, RECOMMAND.RECOMMANDNUM, MEMBER.NICKNAME, "
			+ "MEMBER.ID, COUNT(BOARD.BOARDNUM) AS CNT FROM BOARD "
			+ "LEFT JOIN MEMBER ON BOARD.MEMBERNUM = MEMBER.MEMBERNUM "
			+ "LEFT JOIN RECOMMAND ON BOARD.BOARDNUM = RECOMMAND.BOARDNUM WHERE NICKNAME = ? "
			+ "AND MEMBER.NICKNAME LIKE '%'||?||'%'"
			+ "GROUP BY BOARD.BOARDNUM, MEMBER.MEMBERNUM, BOARD.CATEGORY, BOARD.TITLE, BOARD.BOARDDATE, "
			+ "BOARD.STATE, BOARD.VIEWCOUNT, RECOMMAND.RECOMMANDNUM, MEMBER.NICKNAME, MEMBER.ID "
			+ "ORDER BY BOARD.BOARDNUM DESC";	
	
			--GROUP BY 를 쓸땐 를 하는 모든 것들이 SELECT에 들어가야 에러가안난다....
	SELECT BOARD.BOARDNUM, MEMBER.MEMBERNUM, MEMBER.NICKNAME, 
			MEMBER.ID, BOARD.CATEGORY, BOARD.TITLE, BOARD.CONTENTS, TO_CHAR(BOARD.BOARDDATE, 'YYYY-MM-DD') AS BOARDDATE, BOARD.PRICE, 
			BOARD.IMAGE, BOARD.PRODUCTCATEGORY, BOARD.COMPANY, BOARD.STATE, BOARD.VIEWCOUNT, RECOMMAND.RECOMMANDNUM, COUNT(BOARD.BOARDNUM) AS CNT
			FROM BOARD
			LEFT JOIN MEMBER ON BOARD.MEMBERNUM = MEMBER.MEMBERNUM
			LEFT JOIN RECOMMAND ON BOARD.BOARDNUM = RECOMMAND.BOARDNUM 
		--	WHERE BOARD.BOARDNUM = 1
			GROUP BY BOARD.BOARDNUM, MEMBER.MEMBERNUM, MEMBER.NICKNAME, 
			MEMBER.ID, BOARD.CATEGORY, BOARD.TITLE, BOARD.CONTENTS, BOARD.BOARDDATE, 
			BOARD.PRICE, BOARD.IMAGE, BOARD.PRODUCTCATEGORY,  
			BOARD.COMPANY, BOARD.STATE, BOARD.VIEWCOUNT, RECOMMAND.RECOMMANDNUM;
	

			
			SELECT 
    BOARD.BOARDNUM, 
    MEMBER.MEMBERNUM, 
    MEMBER.NICKNAME, 
    MEMBER.ID, 
    BOARD.CATEGORY, 
    BOARD.TITLE, 
    BOARD.CONTENTS, 
    TO_CHAR(BOARD.BOARDDATE, 'YYYY-MM-DD') AS BOARDDATE, 
    BOARD.PRICE, 
    BOARD.IMAGE, 
    BOARD.PRODUCTCATEGORY, 
    BOARD.COMPANY, 
    BOARD.STATE, 
    BOARD.VIEWCOUNT, 
    RECOMMAND.RECOMMANDNUM, 
    COUNT(BOARD.BOARDNUM) AS CNT
FROM 
    BOARD
    LEFT JOIN MEMBER ON BOARD.MEMBERNUM = MEMBER.MEMBERNUM
    LEFT JOIN RECOMMAND ON BOARD.BOARDNUM = RECOMMAND.BOARDNUM 
WHERE 
    BOARD.BOARDNUM = 1
GROUP BY 
    BOARD.BOARDNUM, 
    MEMBER.MEMBERNUM, 
    MEMBER.NICKNAME, 
    MEMBER.ID, 
    BOARD.CATEGORY, 
    BOARD.TITLE, 
    BOARD.CONTENTS, 
    BOARD.BOARDDATE,
    BOARD.PRICE, 
    BOARD.IMAGE, 
    BOARD.PRODUCTCATEGORY,  
    BOARD.COMPANY, 
    BOARD.STATE, 
    BOARD.VIEWCOUNT, 
    RECOMMAND.RECOMMANDNUM;
    
    
    
    CREATE TABLE REPORT(
	REPORTNUM INT PRIMARY KEY,
	MEMBERNUM INT,
	REPORTER VARCHAR(100),
	SUSPECT VARCHAR(100),
	REPORTCONTENTS VARCHAR(500),
	REPORTDATE DATE DEFAULT SYSDATE,
	ACCOUNTSTOP DATE DEFAULT SYSDATE
);


-------------------------------QUERY TEST---------------------------------

INSERT INTO REPORT (REPORTNUM, MEMBERNUM, REPORTCONTENTS) VALUES(1,1,'가나다');
DROP TABLE REPORT;
VALUES(?)
SELECT TO_CHAR(REPORTDATE,'YYYY-MM-DD'), TO_CHAR(ACCOUNTSTOP,'YYYY-MM-DD') FROM REPORT;

SELECT TO_CHAR(BIRTHDAY,'YYYY-MM-DD') FROM MEMBER;
INSERT INTO REPORT REPORTCONTENTS
SELECT * FROM REPORT;
SELECT M.MEMBERNUM,ID,NICKNAME, BOARDNUM, TITLE, REPORTNUM, REPORTER, SUSPECT, REPORTCONTENTS, REPORTDATE, ACCOUNTSTOP FROM REPORT R JOIN MEMBER M ON M.MEMBERNUM = R.MEMBERNUM JOIN BOARD B ON M.MEMBERNUM = B.MEMBERNUM WHERE M.MEMBERNUM=1;
SELECT REPORTNUM, REPORTER FROM REPORT ORDER BY REPORTNUM DESC;


INSERT INTO REPORT(REPORTNUM, MEMBERNUM, SUSPECT, REPORTER, REPORTCONTENTS) VALUES((SELECT NVL(MAX(REPORTNUM),0)+1 FROM REPORT),2,'3','4','5');